[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
;upload_port = /dev/ttyACM0
 
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
  mcci-catena/MCCI LoRaWAN LMIC library@^4.1.1
  adafruit/Adafruit GFX Library@^1.10.10       ; Biblioteca para gráficos em displays (se necessário)
  adafruit/Adafruit SSD1306@^2.4.6             ; Biblioteca para displays OLED SSD1306
  ;knolleary/PubSubClient@^2.8.0                ; Biblioteca para MQTT, caso você utilize comunicação MQTT
  bblanchon/ArduinoJson@^6.18.3                ; Biblioteca JSON útil para trabalhar com dados de sensores
  olikraus/U8g2@^2.33.15
  ;ThingPulse/ESP8266 and ESP32 OLED Driver for SSD1306 displays@^4.2.0
  https://github.com/ThingPulse/esp8266-oled-ssd1306
  
  adafruit/Adafruit BMP280 Library@^2.6.2  ; Adicione essa linha
  nthnn/PH4502C-Sensor  ; Biblioteca para o sensor de pH